# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html
#
# For latest version of this script goto:
# http://code.projspace.com/axelerant/platform-template

# The name of this app. Must be unique within a project.
name: 'app'

# The runtime the application uses.
type: 'php:8.1'

# Configuration of the build of this application.
build:
    flavor: composer

access:
    ssh: admin

# The build-time dependencies of the app.
dependencies:
    php:
        "composer/composer": "^2"
        "drush/drush": "^11.0"

# Customize php environment variables.
variables:
    php:
        memory_limit: 512M
    env:
        NVM_VERSION: v0.39.1

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `:`.
relationships:
    database: 'mysqldb:mysql'
#    solr: 'solrsearch:solr'
    redis: 'rediscache:redis'

# Add additional PHP extensions.
runtime:
  extensions:
    - redis

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'web'

            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            expires: 5m

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            #
            # Can be true, false or a URI path string.
            passthru: '/index.php'

            # Deny access to static files in this location.
            allow: false

            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true

        '/sites/default/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/default/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/default/files/(css|js)':
                    expires: 2w

        # Block access to non Drupal specific urls to prevent spambots from booting Drupal
        '/wp-login.php':
            allow: false
        '/xmlrpc.php':
            allow: false

# The size of the persistent disk of the application (in MB).
disk: 1536

# The 'mounts' describe writable, persistent filesystem mounts in the application. The keys are
# directory paths, relative to the application root. The values are strings such as
# 'shared:files/NAME', where NAME is just a unique name for the mount.
mounts:
    '/web/sites/default/files': 'shared:files/files'
    '/tmp': 'shared:files/tmp'
    '/private': 'shared:files/private'
    '/drush-backups': 'shared:files/drush-backups'

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      set -e
      unset NPM_CONFIG_PREFIX
      curl -o- https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/install.sh | bash
      export NVM_DIR="$PLATFORM_APP_DIR/.nvm"
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install --lts
      cd web/themes/custom/contribtracker
      npm i
      npm run build
      cd -

    # The deploy hook runs after your application has been deployed and started.
    deploy: |
      cd web
      drush -y deploy

# The configuration of scheduled execution.
crons:
    drupal:
        spec: '*/20 * * * *'
        cmd: 'cd web ; drush core-cron'
