<?php

/**
 * @file
 * Custom contribution tracker module.
 */

/**
 * Implements hook_mail_alter().
 *
 * CONT-36 Disable all mails in non prod environments.
 *
 * We ALLOW mail sending for non platformsh environments.
 * We ALLOW mail for platformsh production envrionments.
 * We DO NOT ALLOW mail sending for non production platformsh environments.
 */
function contrib_tracker_mail_alter(&$message) {
  // Checking if we are on platformsh.
  $projectId = getenv('PLATFORM_PROJECT');
  $branch = getenv('PLATFORM_BRANCH');
  if ($projectId && $branch != 'master') {
    $message['send'] = FALSE;
  }
}

/**
 * Implements hook_theme().
 */
function contrib_tracker_theme($existing) {
  return [
    'views_view__contribution_count__contribution_report' => [
      'base hook' => 'views_view',
    ],
  ];
}

/**
 * Implements hook_preprocess_views_view().
 *
 * CONT-7 Calculate patches and contributions based on filtered result .
 */
function contrib_tracker_preprocess_views_view(&$variables) {
  $view = $variables['view'];
  $rows = $variables['rows'][0]['#rows'] ?? [];
  if ($view->storage->id() == 'contribution_count' &&
    $view->current_display == 'contribution_report') {

    // Total contributions.
    $variables['totalContribution'] = $view->total_rows;

    // Number of total patches.
    $variables['totalPatches'] = array_sum(array_map(fn($rows) => $rows['#row']->_entity->get('field_code_contrib_patches_count')->value, $rows));

    // Number of contributions with at least a single patch.
    $variables['contributionWithPatches'] = count(array_filter($rows, fn($rows) => $rows['#row']->_entity->get('field_code_contrib_patches_count')->value >= 1));
  }
}
